### ISSUE TITLE
Autorun failing to include client side scripts

### ISSUE THREAD

**Issue by mw-voo** [brandonsturgeon/PvPFactions#14]
In File: \lua\autorun\pvpfactions.lua
Line: 

    include "pvpfactions/cl_pvpinit.lua" 

While fail to include the proper client file (Throws file not found error)

**Comment by mw-voo** [comment]
Solved. Was a dumbass and forgot to add to clientside downloads.

**Comment by brandonsturgeon** [comment]
>Well played!
