### ISSUE TITLE
Decision to have PvPFactions remain "pure"

### ISSUE THREAD

**Issue by mw-voo** [brandonsturgeon/PvPFactions#18]
Choice of having it "Pure", install pvpf and only pvpf, or allow it to rely on other libs like ulx's ULib

**Comment by brandonsturgeon** [comment]
I think if it will make things easier/better, then it's absolutely okay to have it rely on other addons.

**Comment by mw-voo** [comment]
Decided to go with copying/crediting Ulysses's code.

**Comment by brandonsturgeon** [comment]
fyi in the future it'd be nice to reference issues when you make a commit. In the commit message just put "#18" to reference Issue #18

**Comment by mw-voo** [comment]
Right now pvpf is in a hectic state of pushing as much code as possible to become a version 1. It would be a ton of shit to cross reference.
