### ISSUE TITLE
Best way to send info between server and client?

### ISSUE THREAD

**Issue by mw-voo** [brandonsturgeon/PvPFactions#19]
Currently, the system in place relies on a table containing all factions.

```
Example Faction in the global table:
   local T = {
        Name = "My Faction"
        ID = "83198281"
        Members = {me, }
        Allies = {}
        Enemies = {}
        Description = "My Pretty Faction"
        Requests = {}
        Invites = {}
        IsPrivate = false
        Stats = { Kills, Deaths } 

    }
```

The current way is just to send the entire table (t) to the client. That is a lot of data, and, if the addon ever hits abuse state, say, 1000 members. Sending that much shit over is a nightmare.

My proposed method is doing something like assigning a byte to each player based on ply1's data.
So according to ply1, a table of online players would be associated to him. Something like:
```
    local players = {
            1 = {player2_name, byte}
            2 = {player3_name, byte}
    }
```

Where byte could be 0 = neutral, 1 = enemy, 2 = allie, 3 = member

Then, we could just send that table of players to clientside and properly draw friendly/enemy or whatnot. 

Another way would just to have multiple versions of SendData(). 

These would be standard whether the above is used or not. (IE: {player_name, byte})

1.   Send entire table
2.   Send just Kill/Death stats
3.   Send Name/Description/Owner

These would be considered extra if the above is not used (IE: {player_name, byte})

1. SendMembers
2. SendAllies
3. SendEnemies

**Comment by brandonsturgeon** [comment]
> Where byte could be 0 = neutral, 1 = enemy, 2 = allie, 3 = member

This is a good idea, but a poor implementation. Just send a string along with the name/steamID of the player. `
1 = {steamID, "ally"}`

Will make things much more clear and the data difference is negligible (for now anyway)

**Comment by mw-voo** [comment]
What about table to json, and send the json over?

Having a huge ass string to parse would be weird. "1 = {steamID, "ally"}, 2 = {steamID,"enemy"}"

**Comment by brandonsturgeon** [comment]
Yeah that's good. Json is relatively size efficient.

**Comment by brandonsturgeon** [comment]
Super neat idea;

We have an API server running externally and we have the clients get data from that instead of our server. Take the load off of our server and put it on a simple, secure API server. That's something I can whip up real quick and get online if you're interested.

**Comment by mw-voo** [comment]
Well our LONG term plan is doing sql. I'm just trying to figure out how to interconnect all this floating data around. Right now, its in a useable state of being in a global table on the server, and saves to a file.txt in DATA. Not a good idea but again, short term goal finished.
